### PR TITLE
Attemt at cleaning up nighty packaging after https://github.com/JuliaLang/julia/pull/5095

### PR DESCRIPTION
**Pull request by ivarne**
Hope this is correct and works. I have not tried it, but the changes seem obvious.

### CODE REVIEW

**Comment by staticfloat** [comment]
Awesome, thanks for the PR!

**Comment by ivarne** [comment]
I think that you should have waited until the Julia PR was merged before merging this. Now your nightly builds will fail. :(

**Comment by staticfloat** [comment]
This is actually the second time I've committed something to this repository thinking that that particular PR was already merged.  I guess I'm just so excited to not have to maintain the `nogit` patch in this repo (the number one source of failures of Ubuntu builds) that my subconscious merged that PR long ago!

**Comment by ivarne** [comment]
I planned to write something to indicate that it wasn't ready to merge, but obviously I forgot.

**Pull request merged**
